### ISSUE TITLE
¿Por qué tu repositorio es público?

### ISSUE THREAD

**Issue by esegredo** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct01-iaas-alu0101202952#1]
@alu0101202952

**Comment by alu0101202952** [comment]
Debido a que estaba haciendo la GitHub Page

**Comment by esegredo** [comment]
@alu0101202952 Andrea, el repositorio puede ser privado, a pesar de que tengas desplegada una Github Page asociada al mismo.

**Comment by alu0101202952** [comment]
Okay, de acuerdo. Gracias
